repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-docstring-first
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: '(^|/)__init__\.py$'

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports", "--ignore-init-module-imports", "--remove-unused-variables", "--ignore-pass-statements", "--in-place"]

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf  # Forbid files containing CRLF end-lines to be committed
      - id: remove-crlf  # Replace CRLF end-lines by LF ones before committing
      - id: forbid-tabs  # Forbid files containing tabs to be committed
      - id: remove-tabs  # Replace tabs by whitespaces before committing
        args: ["--whitespaces-count", "2"]
      - id: chmod
        args: ["644"]
        files: '\.md$'
      - id: insert-license
        files: '\.py$'
        exclude: '^(docs/)'
        args:
          - --license-filepath
          - LICENSES/.license-header
          - --use-current-year
          - --no-extra-eol

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
